name: Build and deploy Node.js app to Azure Web App - meetingcosts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from your repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js version (Node.js 20 LTS)
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 3: Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # Runs the build script in package.json to compile both client and server files

      # Step 4: Zip the build artifacts (including dist and static assets)
      - name: Zip artifact for deployment
        run: zip -r release.zip ./dist package.json node_modules

      # Step 5: Upload the artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      # Step 6: Download the build artifact from the previous job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Step 7: Unzip the artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Step 8: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4911DA76AA6F4C85BAF620C91B7823AC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FE7F3B4D652044D79D656B8F554E23D5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F5EDC86BB37B4C7C82D9905B2211519F }}

      # Step 9: Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'meetingcosts'  # Replace with your actual App Service name
          slot-name: 'Production'
          package: .
